`include"Mem_Macro.v"


`define BUTTEN_ADDR `IOMEM_BASE+0
`define SWITCH0_7_ADDR `IOMEM_BASE+1
`define SWITCH8_15_ADDR `IOMEM_BASE+2

`define LED0_7_ADDR  `IOMEM_BASE+`IOMEMRO_SIZE+0
`define LED8_15_ADDR `IOMEM_BASE+`IOMEMRO_SIZE+1
`define SEG0CS_ADDR  `IOMEM_BASE+`IOMEMRO_SIZE+2
`define SEG0DATA_ADDR  `IOMEM_BASE+`IOMEMRO_SIZE+3
`define SEG1CS_ADDR  `IOMEM_BASE+`IOMEMRO_SIZE+4
`define SEG1DATA_ADDR  `IOMEM_BASE+`IOMEMRO_SIZE+5